caliber:
  port: "443"
  host: "caliber2-mock.revaturelabs.com"
  basepath: "/mock/training/batch"
  protocol: "HTTPS"
  
trainer:
  path: "/trainer"
  
current:
  path: "/current"
  
get-all-trainers:
  path: "/trainers"