#%RAML 1.0 NamedExample

value:
  firstName: "Mock 1027"
  lastName: "Employee 1027"
  email: "mock1027.employee74df14df-5842-4811-a57c-be9836537a40@mock.com"
  trainingBatches:
    - 
      role: "ROLE_LEAD_TRAINER"
      employee:
        email: "mock1027.employee74df14df-5842-4811-a57c-be9836537a40@mock.com"
        firstName: "Mock 1027"
        lastname: "Employee 1027"
      deletedAt: null
    - 
      role: "ROLE_LEAD_TRAINER"
      employee:
        email: "mock1027.employee74df14df-5842-4811-a57c-be9836537a40@mock.com"
        firstName: "Mock 1027"
        lastname: "Employee 1027"
      deletedAt: null
  tier: "ROLE_LEAD_TRAINER"